"""added approved date

Revision ID: 03524dc9710e
Revises: 4972bd4305e6
Create Date: 2022-05-24 14:07:29.782073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03524dc9710e'
down_revision = '4972bd4305e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licence', sa.Column('approved_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licence', 'approved_date')
    # ### end Alembic commands ###
