"""songs model added

Revision ID: 047e24351abe
Revises: 4c8f478f3c04
Create Date: 2022-04-28 18:27:03.113952

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '047e24351abe'
down_revision = '4c8f478f3c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Songs',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('music_title', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('own_recording', sa.Boolean(), nullable=True),
    sa.Column('parties', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('writers', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('publishers', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Songs')
    # ### end Alembic commands ###
