"""“checge_bank_details_types1”

Revision ID: 08dfd8525276
Revises: 1e41c4ed1d7e
Create Date: 2023-02-12 16:42:59.134343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08dfd8525276'
down_revision = '1e41c4ed1d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_details', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('bank_details', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('bank_details', sa.Column('address1', sa.String(length=255), nullable=True))
    op.add_column('bank_details', sa.Column('address2', sa.String(length=255), nullable=True))
    op.add_column('bank_details', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('bank_details', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('bank_details', sa.Column('zip', sa.String(length=255), nullable=True))
    op.add_column('bank_details', sa.Column('phone_number', sa.String(length=255), nullable=True))
    op.add_column('bank_details', sa.Column('ssn', sa.String(length=255), nullable=True))
    op.add_column('bank_details', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_details', 'website')
    op.drop_column('bank_details', 'ssn')
    op.drop_column('bank_details', 'phone_number')
    op.drop_column('bank_details', 'zip')
    op.drop_column('bank_details', 'state')
    op.drop_column('bank_details', 'city')
    op.drop_column('bank_details', 'address2')
    op.drop_column('bank_details', 'address1')
    op.drop_column('bank_details', 'country')
    op.drop_column('bank_details', 'date_of_birth')
    # ### end Alembic commands ###
