"""added seen column to notification table

Revision ID: 1f47154fc12f
Revises: fedc52ca3b24
Create Date: 2022-06-01 11:30:12.038951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f47154fc12f'
down_revision = 'fedc52ca3b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('seen', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'seen')
    # ### end Alembic commands ###
