"""added date time to notification models

Revision ID: 1f7fcabdbf19
Revises: 4a3efedc1a39
Create Date: 2022-06-29 16:49:34.367314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7fcabdbf19'
down_revision = '4a3efedc1a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'datetime')
    # ### end Alembic commands ###
