"""Added similar_tracks table

Revision ID: 2754002eec0f
Revises: 699d74dec1db
Create Date: 2022-05-29 14:44:33.482497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '2754002eec0f'
down_revision = '699d74dec1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_track',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('supervisor_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('search_artistid', sa.String(length=255), nullable=False),
    sa.Column('search_trackid', sa.String(length=255), nullable=False),
    sa.Column('similar_songs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_track')
    # ### end Alembic commands ###
