"""added table  myearnings

Revision ID: 35e2254dfee5
Revises: db0da3716b5a
Create Date: 2022-06-08 15:04:54.232954

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '35e2254dfee5'
down_revision = 'db0da3716b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_earnings',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('artist_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('invoice_id', sa.String(length=255), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.String(length=255), nullable=True),
    sa.Column('balance_amount', sa.String(length=255), nullable=True),
    sa.Column('withdraw_amount', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_earnings')
    # ### end Alembic commands ###
