"""“songs_remove_unused_fields”

Revision ID: 381d34dd71df
Revises: e13739b151be
Create Date: 2023-01-11 17:04:14.859497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381d34dd71df'
down_revision = 'e13739b151be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Songs', 'audio_url')
    op.drop_column('Songs', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Songs', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('Songs', sa.Column('audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
