"""added licensor and producer in licence table

Revision ID: 3d7f2697f310
Revises: a471124e8ad7
Create Date: 2022-06-17 12:11:12.149694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d7f2697f310'
down_revision = 'a471124e8ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licence', sa.Column('licensor', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('licence', sa.Column('producer', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licence', 'producer')
    op.drop_column('licence', 'licensor')
    # ### end Alembic commands ###
