"""deleted songs table

Revision ID: 3fbd61114a56
Revises: cebd9c3e59ac
Create Date: 2022-05-03 15:34:22.556965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fbd61114a56'
down_revision = 'cebd9c3e59ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Songs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Songs',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('music_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('own_recording', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parties', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('writers', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('publishers', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='Songs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Songs_pkey')
    )
    # ### end Alembic commands ###
