"""added json coloumn to songs table

Revision ID: 4466dd27b44e
Revises: 3fbd61114a56
Create Date: 2022-05-03 15:40:06.779522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '4466dd27b44e'
down_revision = '3fbd61114a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Songs',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('music_title', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('own_recording', sa.Boolean(), nullable=True),
    sa.Column('parties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('writers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publishers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Songs')
    # ### end Alembic commands ###
