"""added active_status to user_table

Revision ID: 4a3efedc1a39
Revises: ad714d7c64b3
Create Date: 2022-06-28 17:12:58.327499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3efedc1a39'
down_revision = 'ad714d7c64b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_status')
    # ### end Alembic commands ###
