"""delete songs table

Revision ID: 4c8f478f3c04
Revises: 84a79256c2e3
Create Date: 2022-04-28 18:14:34.048306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c8f478f3c04'
down_revision = '84a79256c2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Songs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Songs',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('music_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('own_recording', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parties', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('writers', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('publishers', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='Songs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Songs_pkey')
    )
    # ### end Alembic commands ###
