"""“add_project_types_to_project”

Revision ID: 4e73bfc03cbc
Revises: 44b5622cf5f5
Create Date: 2023-01-26 17:58:08.533313

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e73bfc03cbc'
down_revision = '44b5622cf5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_type_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_foreign_key(None, 'project', 'project_types', ['project_type_id'], ['id'], ondelete='SET NULL')
    op.drop_column('project', 'project_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'project_type_id')
    # ### end Alembic commands ###
