"""“add_user_id_to_upload_files”

Revision ID: 510b521c7d2d
Revises: 74f78a4538ae
Create Date: 2023-01-09 00:21:17.824144

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510b521c7d2d'
down_revision = '74f78a4538ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_user_files', sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False))
    op.create_foreign_key(None, 'upload_user_files', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload_user_files', type_='foreignkey')
    op.drop_column('upload_user_files', 'user_id')
    # ### end Alembic commands ###
