"""added notification table

Revision ID: 699d74dec1db
Revises: 235f82a595c4
Create Date: 2022-05-27 17:28:21.081723

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '699d74dec1db'
down_revision = '235f82a595c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('song_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('artist_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('music_title', sa.String(length=255), nullable=True),
    sa.Column('track_id', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['Songs.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('licence', sa.Column('search_artistid', sa.String(length=255), nullable=True))
    op.add_column('licence', sa.Column('search_trackid', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licence', 'search_trackid')
    op.drop_column('licence', 'search_artistid')
    op.drop_table('notification')
    # ### end Alembic commands ###
