"""upload audio

Revision ID: 69e6acb117e4
Revises: 934dce3f1618
Create Date: 2022-04-26 16:08:40.690220

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '69e6acb117e4'
down_revision = '934dce3f1618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Upload_audio',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Upload_audio')
    # ### end Alembic commands ###
