"""added date column to myearnings

Revision ID: 6a9da579e68a
Revises: 6b1d5c9b72ff
Create Date: 2022-06-09 15:23:10.015620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9da579e68a'
down_revision = '6b1d5c9b72ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_earnings', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_earnings', 'date')
    # ### end Alembic commands ###
