"""added upload_date in songs table

Revision ID: 6f2176c0e74d
Revises: 3d99823460aa
Create Date: 2022-05-06 14:36:27.341403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2176c0e74d'
down_revision = '3d99823460aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Songs', sa.Column('upload_date', sa.Date(), nullable=True))
    op.add_column('Songs', sa.Column('spotify_id', sa.String(length=255), nullable=True))
    op.add_column('Songs', sa.Column('music_duration', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Songs', 'music_duration')
    op.drop_column('Songs', 'spotify_id')
    op.drop_column('Songs', 'upload_date')
    # ### end Alembic commands ###
