"""“remove_upload_audio_table”

Revision ID: 74f78a4538ae
Revises: b5bf3462421f
Create Date: 2023-01-09 00:20:40.979325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74f78a4538ae'
down_revision = 'b5bf3462421f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Upload_audio')
    op.add_column('upload_user_files', sa.Column('filename', sa.String(length=255), nullable=True))
    op.drop_column('upload_user_files', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_user_files', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('upload_user_files', 'filename')
    op.create_table('Upload_audio',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Upload_audio_pkey')
    )
    # ### end Alembic commands ###
