"""added feedback table

Revision ID: 7681bc92f644
Revises: c600b1914b74
Create Date: 2022-05-12 15:36:04.406805

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7681bc92f644'
down_revision = 'c600b1914b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('easyto_understand', sa.String(length=255), nullable=True),
    sa.Column('songs_satisfaction', sa.String(length=255), nullable=True),
    sa.Column('easyto_navigate', sa.String(length=255), nullable=True),
    sa.Column('licensing_effective', sa.String(length=255), nullable=True),
    sa.Column('improve_ideas', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
