"""alter table  myearnings

Revision ID: 8554b68b3083
Revises: 35e2254dfee5
Create Date: 2022-06-08 16:32:12.334472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8554b68b3083'
down_revision = '35e2254dfee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
