"""second

Revision ID: 934dce3f1618
Revises: 330328e11ace
Create Date: 2022-04-04 20:22:35.928158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934dce3f1618'
down_revision = '330328e11ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_details', sa.Column('reply', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_details', 'reply')
    # ### end Alembic commands ###
