"""added status and remarks in withdrawal

Revision ID: a471124e8ad7
Revises: 38e0401ec7fb
Create Date: 2022-06-15 20:10:28.961048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a471124e8ad7'
down_revision = '38e0401ec7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('withdrawal', sa.Column('remarks', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawal', 'remarks')
    op.drop_column('withdrawal', 'status')
    # ### end Alembic commands ###
