"""added song_id to payment table

Revision ID: ad714d7c64b3
Revises: dcd654518f68
Create Date: 2022-06-27 12:53:33.380079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad714d7c64b3'
down_revision = 'dcd654518f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('song_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'song_id')
    # ### end Alembic commands ###
