"""added account_id to user table

Revision ID: bd94ab96c7a3
Revises: fcc8503cb588
Create Date: 2022-06-15 17:11:28.726951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd94ab96c7a3'
down_revision = 'fcc8503cb588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_id')
    # ### end Alembic commands ###
