"""added status to songtable

Revision ID: c4417f931d21
Revises: 03524dc9710e
Create Date: 2022-05-25 13:46:18.287874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4417f931d21'
down_revision = '03524dc9710e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Songs', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Songs', 'status')
    # ### end Alembic commands ###
