"""added likes and dislike table

Revision ID: c600b1914b74
Revises: 6f2176c0e74d
Create Date: 2022-05-09 15:44:01.328137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'c600b1914b74'
down_revision = '6f2176c0e74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count_likes',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('song_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['Songs.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('count_likes')
    # ### end Alembic commands ###
