"""added cover photo column

Revision ID: cebd9c3e59ac
Revises: 0feeeb25bd42
Create Date: 2022-04-29 15:06:36.838838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebd9c3e59ac'
down_revision = '0feeeb25bd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cover_photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cover_photo')
    # ### end Alembic commands ###
