"""“add_zip_to_user”

Revision ID: d00e94f74bf3
Revises: de6a1170f027
Create Date: 2023-01-18 08:10:49.685665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00e94f74bf3'
down_revision = 'de6a1170f027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zip', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip')
    # ### end Alembic commands ###
