"""deleted card details

Revision ID: d2ea8da1da46
Revises: 1f7fcabdbf19
Create Date: 2022-07-06 16:17:52.012495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ea8da1da46'
down_revision = '1f7fcabdbf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'expyear')
    op.drop_column('payment', 'cardnumber')
    op.drop_column('payment', 'cvv')
    op.drop_column('payment', 'expmonth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('expmonth', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('cvv', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('cardnumber', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('expyear', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
