"""added spotifyid to songtable

Revision ID: da244280abdc
Revises: c4417f931d21
Create Date: 2022-05-25 16:58:50.002035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da244280abdc'
down_revision = 'c4417f931d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
