"""added spotify user_name to user table

Revision ID: db0da3716b5a
Revises: e5c2bf526d0e
Create Date: 2022-06-06 16:41:58.234271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0da3716b5a'
down_revision = 'e5c2bf526d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('spotify_user_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'spotify_user_name')
    # ### end Alembic commands ###
