"""added columns in payment

Revision ID: dcd654518f68
Revises: e49f52e03497
Create Date: 2022-06-26 22:26:07.373514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd654518f68'
down_revision = 'e49f52e03497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('receipt_url', sa.String(length=500), nullable=True))
    op.add_column('payment', sa.Column('receipt_created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'receipt_created_date')
    op.drop_column('payment', 'receipt_url')
    # ### end Alembic commands ###
