"""“add_extra_fields_to_user_and_license”

Revision ID: de6a1170f027
Revises: 381d34dd71df
Create Date: 2023-01-17 23:35:46.928767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6a1170f027'
down_revision = '381d34dd71df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licence', sa.Column('step', sa.Integer(), nullable=True))
    op.add_column('licence', sa.Column('is_finished', sa.Boolean(), nullable=True))
    op.add_column('licence', sa.Column('licence_agreement', sa.Boolean(), nullable=True))
    op.add_column('licence', sa.Column('payment_status', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('writerPRO', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('writerIPI', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('publisherName', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('publisherPRO', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('publisherIPI', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('label', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'city')
    op.drop_column('user', 'state')
    op.drop_column('user', 'country')
    op.drop_column('user', 'label')
    op.drop_column('user', 'publisherIPI')
    op.drop_column('user', 'publisherPRO')
    op.drop_column('user', 'publisherName')
    op.drop_column('user', 'writerIPI')
    op.drop_column('user', 'writerPRO')
    op.drop_column('licence', 'payment_status')
    op.drop_column('licence', 'licence_agreement')
    op.drop_column('licence', 'is_finished')
    op.drop_column('licence', 'step')
    # ### end Alembic commands ###
