"""“add_artist_title_to_songs”

Revision ID: e13739b151be
Revises: 510b521c7d2d
Create Date: 2023-01-09 03:26:15.338624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13739b151be'
down_revision = '510b521c7d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Songs', sa.Column('artist_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Songs', 'artist_title')
    # ### end Alembic commands ###
