"""added amount_before_reduction to payment table

Revision ID: e49f52e03497
Revises: 3d7f2697f310
Create Date: 2022-06-22 17:40:50.164181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49f52e03497'
down_revision = '3d7f2697f310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('amount_before_reduction', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'amount_before_reduction')
    # ### end Alembic commands ###
