"""added invoice table

Revision ID: e5854bfe258f
Revises: 1f47154fc12f
Create Date: 2022-06-01 12:07:16.993320

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e5854bfe258f'
down_revision = '1f47154fc12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supervisor_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('song_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('Licence_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Licence_id'], ['licence.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['song_id'], ['Songs.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    # ### end Alembic commands ###
