"""payment table created

Revision ID: e5c2bf526d0e
Revises: e5854bfe258f
Create Date: 2022-06-06 15:00:58.575945

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e5c2bf526d0e'
down_revision = 'e5854bfe258f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supervisor_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cardnumber', sa.String(length=255), nullable=True),
    sa.Column('expmonth', sa.String(length=255), nullable=True),
    sa.Column('expyear', sa.String(length=255), nullable=True),
    sa.Column('cvv', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
