"""“songs_add_credits”

Revision ID: f0477a3e0641
Revises: b33fcfcb6329
Create Date: 2023-01-24 21:42:46.434098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0477a3e0641'
down_revision = 'b33fcfcb6329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Songs', sa.Column('writing_credits', sa.Integer(), nullable=True))
    op.add_column('Songs', sa.Column('publisher_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Songs', 'publisher_credits')
    op.drop_column('Songs', 'writing_credits')
    # ### end Alembic commands ###
