"""contact table altered 

Revision ID: fcc8503cb588
Revises: 6a9da579e68a
Create Date: 2022-06-13 14:49:10.765723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc8503cb588'
down_revision = '6a9da579e68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_details', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('contact_details', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('contact_details', sa.Column('number_of_employees', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_details', 'number_of_employees')
    op.drop_column('contact_details', 'company_name')
    op.drop_column('contact_details', 'last_name')
    # ### end Alembic commands ###
