"""Remove relationship from similar track

Revision ID: fedc52ca3b24
Revises: 9ad70a163913
Create Date: 2022-05-30 15:52:27.517625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedc52ca3b24'
down_revision = '9ad70a163913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
